spring:
  security:
    oauth2:
      kakao:
        request-uri: https://kapi.kakao.com/v2/user/me
      apple:
        key-uri: https://appleid.apple.com/auth/keys
        issuer: https://appleid.apple.com
        client-id: ${APPLE_CLIENT_ID}