spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - optional:classpath:/application-oauth.yml
  server:
    # address: localhost
    port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URL}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: ${REDIS_HOST}
    port: 6379
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none # create
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  task:
    scheduling:
      pool:
        size: 4
jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  bearer:
    header: "Bearer "
  access-token:
    header: Authorization
    validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token:
    header: Refresh
    validity: ${JWT_REFRESH_TOKEN_VALIDITY}
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: false
fcm:
  key: ${FCM_KEY}
  scope: https://www.googleapis.com/auth/firebase.messaging
slack:
  url: ${SLACK_URL}
file:
  base-path: "/Users/kakao/Desktop/pyonsnal-project/review"
